# Generated by Django 5.2.14 on 2026-05-27 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_label', models.CharField(blank=True, max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.branch')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_shifts', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clock_in_at', models.DateTimeField()),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('clocked_in', 'Clocked In'), ('clocked_out', 'Clocked Out'), ('exception', 'Exception')], default='clocked_in', max_length=32)),
                ('exception_note', models.TextField(blank=True)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.branch')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='workforce.shift')),
            ],
            options={
                'ordering': ['-clock_in_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('scheduled_minutes', models.PositiveIntegerField(default=0)),
                ('worked_minutes', models.PositiveIntegerField(default=0)),
                ('task_minutes', models.PositiveIntegerField(default=0)),
                ('exception_count', models.PositiveIntegerField(default=0)),
                ('payroll_ready', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('needs_correction', 'Needs Correction')], default='draft', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_summaries', to='core.branch')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_timesheets', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', 'staff_user__email'],
            },
        ),
        migrations.CreateModel(
            name='HandoverNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed')], default='open', max_length=32)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_handover_notes', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_handover_notes', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_notes', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_notes', to='core.branch')),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at'],
                'indexes': [models.Index(fields=['branch', 'status'], name='workforce_h_branch__c62762_idx'), models.Index(fields=['assigned_to', 'status'], name='workforce_h_assigne_79a781_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('carers', 'Carers'), ('unpaid', 'Unpaid'), ('other', 'Other')], default='annual', max_length=32)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='core.branch')),
                ('related_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='tickets.ticket')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['staff_user', 'status'], name='workforce_l_staff_u_565381_idx'), models.Index(fields=['branch', 'status'], name='workforce_l_branch__206413_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['staff_user', 'starts_at'], name='workforce_s_staff_u_291e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['branch', 'status'], name='workforce_s_branch__5b7653_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['staff_user', 'status'], name='workforce_a_staff_u_4c00c5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['branch', 'clock_in_at'], name='workforce_a_branch__dd6a45_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheetsummary',
            index=models.Index(fields=['branch', 'status'], name='workforce_t_branch__85759a_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheetsummary',
            index=models.Index(fields=['staff_user', 'period_start'], name='workforce_t_staff_u_b7b9fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='timesheetsummary',
            constraint=models.UniqueConstraint(fields=('staff_user', 'period_start', 'period_end'), name='unique_timesheet_period_per_staff'),
        ),
    ]
