# Generated by Django 5.2.14 on 2026-05-27 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('entities', '0002_entitylifecycleevent_onboardingworkflowtemplate_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('part_received', 'Part Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('expected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.branch')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='entities.entity')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=120)),
                ('barcode', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(default='each', max_length=40)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reorder_threshold', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('low_stock', 'Low Stock'), ('archived', 'Archived')], default='active', max_length=32)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.branch')),
                ('entity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_item', to='entities.entity')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_stock_items', to='entities.entity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_ordered', models.PositiveIntegerField(default=1)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchaseorder')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_lines', to='inventory.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=120)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['expiry_date', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('supplier_issue', models.TextField(blank=True)),
                ('damage_quantity', models.PositiveIntegerField(default=0)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_receipts', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='inventory.inventorybatch')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='inventory.purchaseorder')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('target_type', models.CharField(choices=[('stock_item', 'Stock Item'), ('batch', 'Batch'), ('purchase_order', 'Purchase Order'), ('delivery', 'Delivery')], max_length=32)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='inventory.deliveryreceipt')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='inventory.inventorybatch')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='inventory.purchaseorder')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['barcode'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('adjustment', 'Adjustment'), ('damage', 'Damage'), ('transfer', 'Transfer')], max_length=32)),
                ('quantity_delta', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventorybatch')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('related_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='tickets.ticket')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['branch', 'status'], name='inventory_p_branch__9688af_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['branch', 'status'], name='inventory_s_branch__063cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['barcode'], name='inventory_s_barcode_f5639f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('branch', 'sku'), name='unique_stock_item_sku_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'stock_item'), name='unique_po_line_stock_item'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['expiry_date'], name='inventory_i_expiry__e4a18c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybatch',
            constraint=models.UniqueConstraint(fields=('stock_item', 'batch_number'), name='unique_batch_per_stock_item'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', 'movement_type'], name='inventory_s_stock_i_3f90c4_idx'),
        ),
    ]
