# Generated by Django 5.2.14 on 2026-05-26 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('employee', 'Employee'), ('doctor', 'Doctor / Practitioner'), ('contractor', 'Contractor'), ('supplier', 'Supplier'), ('patient_reference', 'Patient Reference'), ('ai_agent', 'AI Agent'), ('inventory_item', 'Inventory Item'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('device', 'Device'), ('room', 'Room'), ('branch', 'Branch'), ('contract', 'Contract'), ('service', 'Service'), ('digital_asset', 'Digital Asset')], max_length=64)),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('qr_code_value', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='core.branch')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_entities', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AssetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_tag', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('maintenance_status', models.CharField(default='unknown', max_length=80)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_profile', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_code', models.CharField(max_length=120, unique=True)),
                ('human_review_required', models.BooleanField(default=True)),
                ('allowed_actions', models.JSONField(blank=True, default=list)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agent_profile', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItemProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('barcode', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('reorder_threshold', models.PositiveIntegerField(default=0)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_profile', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientReferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_reference', models.CharField(max_length=120, unique=True)),
                ('preferred_contact_channel', models.CharField(blank=True, max_length=40)),
                ('masked_contact', models.CharField(blank=True, max_length=120)),
                ('consent_status', models.CharField(default='unknown', max_length=80)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employment_type', models.CharField(blank=True, max_length=80)),
                ('onboarding_status', models.CharField(default='not_started', max_length=80)),
                ('payroll_status', models.CharField(default='not_ready', max_length=80)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='entities.entity')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_code', models.CharField(blank=True, max_length=80)),
                ('payment_status', models.CharField(default='not_ready', max_length=80)),
                ('compliance_status', models.CharField(default='pending', max_length=80)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entity_type', 'status'], name='entities_en_entity__f17f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['branch', 'status'], name='entities_en_branch__5b3347_idx'),
        ),
    ]
