# Generated by Django 5.2.14 on 2026-05-26 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('entities', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_lifecycle_changes', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='entities.entity')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingWorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('employee', 'Employee'), ('doctor', 'Doctor / Practitioner'), ('contractor', 'Contractor'), ('supplier', 'Supplier'), ('patient_reference', 'Patient Reference'), ('ai_agent', 'AI Agent'), ('inventory_item', 'Inventory Item'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('device', 'Device'), ('room', 'Room'), ('branch', 'Branch'), ('contract', 'Contract'), ('service', 'Service'), ('digital_asset', 'Digital Asset')], max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['entity_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'name'), name='unique_onboarding_template_name_per_type')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('profile', 'Profile'), ('document', 'Document'), ('approval', 'Approval'), ('training', 'Training'), ('equipment', 'Equipment'), ('qr_barcode', 'QR / Barcode'), ('review', 'Review')], max_length=40)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('ticket_category', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_step_templates', to='documents.documenttemplate')),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='entities.onboardingworkflowtemplate')),
            ],
            options={
                'ordering': ['workflow_template', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EntityOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('waiting_approval', 'Waiting Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('activation_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_onboardings', to='tickets.ticket')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_entity_onboardings', to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='entities.entity')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_entity_onboardings', to=settings.AUTH_USER_MODEL)),
                ('workflow_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_runs', to='entities.onboardingworkflowtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingStepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('profile', 'Profile'), ('document', 'Document'), ('approval', 'Approval'), ('training', 'Training'), ('equipment', 'Equipment'), ('qr_barcode', 'QR / Barcode'), ('review', 'Review')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('verified', 'Verified'), ('needs_correction', 'Needs Correction'), ('waived', 'Waived')], default='pending', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('evidence_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_steps', to=settings.AUTH_USER_MODEL)),
                ('document_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_steps', to='documents.documentassignment')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='entities.entityonboarding')),
                ('related_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_steps', to='tickets.ticket')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_onboarding_steps', to=settings.AUTH_USER_MODEL)),
                ('step_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='entities.onboardingsteptemplate')),
            ],
            options={
                'ordering': ['onboarding', 'id'],
                'indexes': [models.Index(fields=['status', 'step_type'], name='entities_on_status_95c7b5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='onboardingsteptemplate',
            constraint=models.UniqueConstraint(fields=('workflow_template', 'order'), name='unique_onboarding_step_order_per_template'),
        ),
        migrations.AddIndex(
            model_name='entityonboarding',
            index=models.Index(fields=['status', 'started_at'], name='entities_en_status_efdb28_idx'),
        ),
    ]
