# Generated by Django 5.2.14 on 2026-05-26 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('employment_agreement', 'Employment Agreement'), ('contractor_agreement', 'Contractor Agreement'), ('practitioner_agreement', 'Practitioner Agreement'), ('supplier_agreement', 'Supplier Agreement'), ('confidentiality', 'Confidentiality Agreement'), ('privacy_acknowledgement', 'Privacy Acknowledgement'), ('ai_usage', 'AI Usage Acknowledgement'), ('patient_consent', 'Patient Consent'), ('policy', 'Policy Acknowledgement')], max_length=80)),
                ('description', models.TextField(blank=True)),
                ('current_version', models.CharField(default='1.0', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('version', models.CharField(default='1.0', max_length=40)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='documents.documenttemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('viewed', 'Viewed'), ('acknowledged', 'Acknowledged'), ('signed', 'Signed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='assigned', max_length=32)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_assignments', to='entities.entity')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_assignments', to=settings.AUTH_USER_MODEL)),
                ('signed_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_assignments', to='documents.documentfile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.documenttemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'due_at'], name='documents_d_status_f08a18_idx'), models.Index(fields=['assigned_to_user', 'status'], name='documents_d_assigne_fbf072_idx'), models.Index(fields=['assigned_to_entity', 'status'], name='documents_d_assigne_ca12c3_idx')],
            },
        ),
    ]
