# Generated by Django 5.2.14 on 2026-05-27 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('entities', '0002_entitylifecycleevent_onboardingworkflowtemplate_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('privacy', 'Privacy'), ('ai_usage', 'AI Usage'), ('patient_communication', 'Patient Communication'), ('telehealth', 'Telehealth'), ('general', 'General')], max_length=80)),
                ('status', models.CharField(choices=[('given', 'Given'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='given', max_length=32)),
                ('purpose', models.CharField(max_length=255)),
                ('scope', models.TextField(blank=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('expired', 'Expired'), ('waived', 'Waived')], default='assigned', max_length=32)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True)),
                ('quiz_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('certificate_label', models.CharField(blank=True, max_length=255)),
                ('evidence_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('module_type', models.CharField(choices=[('privacy', 'Privacy'), ('cyber_security', 'Cyber Security'), ('emergency', 'Emergency'), ('ai_governance', 'AI Governance'), ('infection_control', 'Infection Control'), ('barcode_inventory', 'Barcode and Inventory'), ('policy', 'Policy'), ('general', 'General')], default='general', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=40)),
                ('validity_days', models.PositiveIntegerField(default=365)),
                ('quiz_required', models.BooleanField(default=False)),
                ('certificate_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='acknowledgement_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='evidence_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='renewal_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_renewals', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='version',
            field=models.CharField(default='1.0', max_length=40),
        ),
        migrations.AddIndex(
            model_name='documentassignment',
            index=models.Index(fields=['status', 'expires_at'], name='documents_d_status_aae9f7_idx'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='document_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='documents.documentassignment'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_consent_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='subject_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='subject_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='assigned_to_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_assignments', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_training_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingassignment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='documents.trainingmodule'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['consent_type', 'status'], name='documents_c_consent_c0aceb_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['subject_user', 'status'], name='documents_c_subject_37a9da_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['subject_entity', 'status'], name='documents_c_subject_4bb18d_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['status', 'due_at'], name='documents_t_status_5a5dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['status', 'expires_at'], name='documents_t_status_4cfd47_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['assigned_to_user', 'status'], name='documents_t_assigne_6dde78_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['assigned_to_entity', 'status'], name='documents_t_assigne_ae8935_idx'),
        ),
    ]
